@userUrl = http//localhot:8080/api/{{ownerId}}/queue
@ownerId = twUYr3EHO2fm45THYXokG5OxcK63
@deviceToken = firebase_device_token

### 待ち順に参加する
GET {{userUrl}}/position/?token={{{{deviceToken}}}}

### あと何人かがわかる
GET {{userUrl}}/following/?&position=3

### 列から抜ける
DELETE {{userUrl}}/position/?dposition=3
