@userUrl = https://dxwaitingtime-backend.kajilab.tk/api/{{ownerId}}/queue
@ownerId = awoO21MPlEc3iXOTSYKGBfZiTrr1
@deviceToken = eTfjKrNyWXIxnYIx5Wt9gM:APA91bG8_FJ6zcD_8cRCjybY3cgHpTZLhz_QjuKLZyeCAScLS1lYBoSuAAYvAS4KdHlwD0sCCBkYvX6NHXf1yFH8k_zeUqjrfeE0cwx6Kyb5EVGsLNuZbtFjoHIOd6Ntl59-MhQIFp2_

### 待ち順に参加する
GET {{userUrl}}/position?deviceToken={{deviceToken}}

### あと何人かがわかる
GET {{userUrl}}/following?deviceToken={{deviceToken}}

### 列から抜ける
DELETE {{userUrl}}/position?callNumber=1
