name: Yarn Build and Lint

on:
  push:
    branches:
      - "*"

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install
        working-directory: ./frontend

      - name: Build
        run: yarn build
        working-directory: ./frontend

      - name: Run lint
        run: yarn lint
        working-directory: ./frontend

      # Notify Slack on success
      - name: Notify Slack on success
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: good
        with:
          status: ${{ job.status }}
          fields: repo,commit,author,action,eventName,ref,workflow,status
          message: |
            The build and lint succeeded in branch ${{ github.ref }} of repository ${{ github.repository }}.

      # Notify Slack on failure
      - name: Notify Slack on failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: danger
        with:
          status: ${{ job.status }}
          fields: repo,commit,author,action,eventName,ref,workflow,status
          message: |
            The build or lint has failed in branch ${{ github.ref }} of repository ${{ github.repository }}.
