name: Yarn Build and Lint

on:
  push:
    paths:
      - "frontend/**"

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install
        working-directory: ./frontend

      - name: Build
        run: yarn build
        working-directory: ./frontend

      - name: Run lint
        run: yarn lint
        working-directory: ./frontend
